
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: spring
    password: p@ssword
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
